name: Insomnia CI (Inso tests)

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL for API under test'
        required: false
        default: 'http://localhost:8000'
      start_api:
        description: 'start app in this job? true/false'
        required: false
        default: 'false'

jobs:
  inso-tests:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ github.event.inputs.base_url || 'http://localhost:8000' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: (Optional) Start API in background
        if: ${{ github.event.inputs.start_api == 'true' }}
        run: |
          # adjust these commands to your repo's start routine
          pip install -r requirements.txt
          nohup python -m uvicorn app:app --host 0.0.0.0 --port 8000 &>/tmp/uvicorn.log &
          # simple readiness probe
          for i in $(seq 1 30); do
            if curl -sSf "${{ env.BASE_URL }}" >/dev/null 2>&1; then
              echo "API is up"
              break
            fi
            echo "Waiting... ($i)"
            sleep 1
          done

      - name: Run Inso tests (Docker)
        run: |
          docker run --rm -v "${{ github.workspace }}:/work" -w /work \
            kong/inso:latest \
            inso run test "Deprecated Routes" --env "Base Environment" --env-var baseUrl=${{ env.BASE_URL }}
