name: CI (tests only)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      # Fast Python setup with uv
      - uses: astral-sh/setup-uv@v6
      - run: uv python install
      - run: uv venv && uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -q
