name: CI (tests only)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          for v in OPENAI_API_KEY; do
            if [ -z "${!v}" ]; then
              echo "❌ Missing $v (not delivered to this run)."
              exit 1
            fi
          done
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # Fast Python setup with uv
      - uses: astral-sh/setup-uv@v6
      - run: uv python install
      - run: uv venv && uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -q
